env:
  RUBY_VERSION: 2.7.1

name: rspec
on: [push,pull_request]
jobs:
  rspec-test:
    name: tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Create database
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake
